https://academia.stackexchange.com
https://academia.stackexchange.com/questions/167739/can-professors-generally-keep-books-paid-for-with-university-funds
https://academia.stackexchange.com/questions/167793/is-it-bad-not-to-answer-the-tell-me-how-you-behaved-in-a-situation-of-conflict
https://academia.stackexchange.com/questions/tagged/advisor
https://academia.stackexchange.com/questions/tagged/books
https://academia.stackexchange.com/questions/tagged/interview
https://academia.stackexchange.com/questions/tagged/phd
https://academia.stackexchange.com/questions/tagged/professors
https://academia.stackexchange.com/questions/tagged/publications
https://academia.stackexchange.com/questions/tagged/research-process
https://academia.stackexchange.com/questions/tagged/united-states
https://academia.stackexchange.com/users/137802/bird
https://academia.stackexchange.com/users/586/embarrassed-tenured-professor
https://ai.stackexchange.com
https://android.stackexchange.com
https://anime.stackexchange.com
https://api.stackexchange.com
https://apple.stackexchange.com
https://apple.stackexchange.com/questions/tagged/time-machine
https://arduino.stackexchange.com
https://astronomy.stackexchange.com
https://astronomy.stackexchange.com/questions/43829/can-you-see-something-active-in-the-sky-apart-from-satellites-can-there-be-amat
https://astronomy.stackexchange.com/questions/tagged/star
https://astronomy.stackexchange.com/questions/tagged/supernova
https://astronomy.stackexchange.com/questions/tagged/telescope
https://astronomy.stackexchange.com/questions/tagged/time-domain-astronomy
https://astronomy.stackexchange.com/users/39332/danieloftaebl
https://aviation.stackexchange.com
https://aviation.stackexchange.com/questions/87186/what-is-the-exact-meaning-of-manoeuvring-when-said-by-atc-in-reference-to-traf
https://aviation.stackexchange.com/questions/tagged/icao
https://aviation.stackexchange.com/questions/tagged/phraseology
https://aviation.stackexchange.com/questions/tagged/radio-communications
https://aviation.stackexchange.com/users/57499/opr
https://bicycles.stackexchange.com
https://bicycles.stackexchange.com/questions/76836/areas-to-mask-when-painting-a-bike
https://bicycles.stackexchange.com/questions/tagged/bags
https://bicycles.stackexchange.com/questions/tagged/paintjob
https://biology.stackexchange.com
https://bitcoin.stackexchange.com
https://blender.stackexchange.com
https://blender.stackexchange.com/questions/222811/compressional-wave-in-a-cube
https://blender.stackexchange.com/questions/tagged/mesh
https://boardgames.stackexchange.com
https://bricks.stackexchange.com
https://bricks.stackexchange.com/questions/tagged/part-identification
https://bricks.stackexchange.com/users/18317/petz
https://chat.stackexchange.com?tab=site&host=stackexchange.com
https://chemistry.stackexchange.com
https://chemistry.stackexchange.com/questions/tagged/alcohols
https://chemistry.stackexchange.com/questions/tagged/organic-chemistry
https://chemistry.stackexchange.com/users/109519/arpan
https://chess.stackexchange.com
https://chess.stackexchange.com/questions/tagged/bishops
https://chess.stackexchange.com/users/20677/llama
https://chinese.stackexchange.com
https://christianity.stackexchange.com
https://codegolf.stackexchange.com
https://codegolf.stackexchange.com/questions/225769/sum-of-first-n-terms-of-this-series
https://codegolf.stackexchange.com/questions/225808/interpret-underload
https://codegolf.stackexchange.com/questions/225818/i-give-you-ascii-art-you-make-it-pseudo-3d
https://codegolf.stackexchange.com/questions/225857/exact-generalised-harmonic-numbers
https://codegolf.stackexchange.com/questions/tagged/3d
https://codegolf.stackexchange.com/questions/tagged/ascii-art
https://codegolf.stackexchange.com/questions/tagged/code-golf
https://codegolf.stackexchange.com/questions/tagged/interpreter
https://codegolf.stackexchange.com/questions/tagged/math
https://codegolf.stackexchange.com/questions/tagged/rational-numbers
https://codegolf.stackexchange.com/questions/tagged/sequence
https://codegolf.stackexchange.com/questions/tagged/underload
https://codegolf.stackexchange.com/questions/tagged/unicode
https://codegolf.stackexchange.com/users/103495/nph
https://codegolf.stackexchange.com/users/103693/zerocodeexception
https://codegolf.stackexchange.com/users/103955/java-learner
https://codegolf.stackexchange.com/users/66833/caird-coinheringaahing
https://codereview.stackexchange.com
https://codereview.stackexchange.com/questions/tagged/caesar-cipher
https://codereview.stackexchange.com/questions/tagged/python
https://coffee.stackexchange.com
https://cooking.stackexchange.com
https://cooking.stackexchange.com/questions/115697/why-not-incorporating-eggs-at-the-last-moment-when-making-crepes
https://cooking.stackexchange.com/questions/115706/flatbread-dough-turned-red
https://cooking.stackexchange.com/questions/tagged/color
https://cooking.stackexchange.com/questions/tagged/eggs
https://cooking.stackexchange.com/questions/tagged/food-safety
https://cooking.stackexchange.com/questions/tagged/frying
https://cooking.stackexchange.com/questions/tagged/meat
https://cooking.stackexchange.com/questions/tagged/pancakes
https://cooking.stackexchange.com/users/27549/yulia-v
https://cooking.stackexchange.com/users/93942/baster
https://crypto.stackexchange.com
https://cs.stackexchange.com
https://cstheory.stackexchange.com
https://cstheory.stackexchange.com/questions/48962/does-univ-univ-always-lead-to-contradiction-in-a-dependently-typed-language
https://cstheory.stackexchange.com/questions/tagged/dependent-type
https://cstheory.stackexchange.com/questions/tagged/type-theory
https://data.stackexchange.com
https://datascience.stackexchange.com
https://datascience.stackexchange.com/questions/94599/is-there-a-node-embedding-method-that-is-portable-between-graphs
https://datascience.stackexchange.com/questions/tagged/embeddings
https://datascience.stackexchange.com/questions/tagged/graphs
https://dba.stackexchange.com
https://dba.stackexchange.com/questions/291751/how-to-find-the-shortest-path-between-two-currencies
https://devops.stackexchange.com
https://devops.stackexchange.com/questions/13947/log-data-rotation-in-docker-container
https://devops.stackexchange.com/questions/tagged/docker-compose
https://devops.stackexchange.com/questions/tagged/monitoring
https://diy.stackexchange.com
https://diy.stackexchange.com/questions/tagged/electrical
https://diy.stackexchange.com/questions/tagged/screws
https://diy.stackexchange.com/users/120147/p2000
https://drones.stackexchange.com
https://drupal.stackexchange.com
https://dsp.stackexchange.com
https://ebooks.stackexchange.com
https://economics.stackexchange.com
https://economics.stackexchange.com/questions/44005/why-are-cost-functions-often-assumed-to-be-convex-in-microeconomics
https://economics.stackexchange.com/questions/tagged/cost-functions
https://economics.stackexchange.com/questions/tagged/microeconomics
https://economics.stackexchange.com/questions/tagged/producer-theory
https://economics.stackexchange.com/users/4230/richard-hardy
https://electronics.stackexchange.com
https://electronics.stackexchange.com/questions/565596/electricity-only-flows-in-a-complete-circuit-so-how-does-tdr-time-domain-refle
https://electronics.stackexchange.com/questions/tagged/manufacturing
https://electronics.stackexchange.com/questions/tagged/manufacturing-process
https://electronics.stackexchange.com/questions/tagged/tdr
https://electronics.stackexchange.com/users/284203/lenapark
https://electronics.stackexchange.com/users/285830/jason
https://ell.stackexchange.com
https://ell.stackexchange.com/questions/284410/what-does-the-sentence-haptic-feedback-on-your-device-gives-the-game-a-satisfyi
https://ell.stackexchange.com/questions/tagged/meaning
https://ell.stackexchange.com/questions/tagged/meaning-in-context
https://ell.stackexchange.com/questions/tagged/sentence-meaning
https://ell.stackexchange.com/users/21367/curious
https://emacs.stackexchange.com
https://engineering.stackexchange.com
https://english.stackexchange.com
https://english.stackexchange.com/questions/567251/how-to-differentiate-slow-vs-slowly-both-as-adverbs
https://english.stackexchange.com/questions/tagged/flat-adverbs
https://english.stackexchange.com/questions/tagged/terminology
https://english.stackexchange.com/questions/tagged/word-choice
https://english.stackexchange.com/users/52134/safira
https://ethereum.stackexchange.com
https://expressionengine.stackexchange.com
https://fitness.stackexchange.com
https://freelancing.stackexchange.com
https://french.stackexchange.com
https://french.stackexchange.com/questions/tagged/n%c3%a9gation
https://french.stackexchange.com/users/22459/le-anh-dung
https://gamedev.stackexchange.com
https://gaming.stackexchange.com
https://gaming.stackexchange.com/questions/386061/can-your-computer-steam-account-get-hacked-by-redeeming-a-steam-wallet-code-sent
https://gaming.stackexchange.com/questions/386073/what-game-is-played-in-the-2021-virgin-media-advert
https://gaming.stackexchange.com/questions/tagged/game-identification
https://gaming.stackexchange.com/questions/tagged/steam
https://gaming.stackexchange.com/users/272278/diecie
https://gardening.stackexchange.com
https://genealogy.stackexchange.com
https://german.stackexchange.com
https://gis.stackexchange.com
https://gis.stackexchange.com/questions/396825/qgis-label-function-to-get-a-value-from-an-other-layer
https://gis.stackexchange.com/questions/396828/using-case-statement-with-two-strings-in-qgis
https://gis.stackexchange.com/questions/tagged/grouping
https://gis.stackexchange.com/questions/tagged/intersection
https://gis.stackexchange.com/users/145164/stocker-antoine
https://graphicdesign.stackexchange.com
https://hardwarerecs.stackexchange.com
https://hermeneutics.stackexchange.com
https://hermeneutics.stackexchange.com/questions/60450/are-1-john-18-and-1-john-39-contradictory
https://hermeneutics.stackexchange.com/users/23182/gon%c3%a7alo-peres-%e9%be%9a%e7%87%bf%e7%a6%84
https://hinduism.stackexchange.com/questions/tagged/krishna
https://hinduism.stackexchange.com/questions/tagged/mahabharata
https://hinduism.stackexchange.com/questions/tagged/naraka
https://hinduism.stackexchange.com/questions/tagged/swarga
https://history.stackexchange.com
https://history.stackexchange.com/questions/tagged/crusades
https://homebrew.stackexchange.com
https://hsm.stackexchange.com
https://islam.stackexchange.com
https://japanese.stackexchange.com
https://joomla.stackexchange.com
https://judaism.stackexchange.com
https://korean.stackexchange.com
https://languagelearning.stackexchange.com
https://latin.stackexchange.com/questions/tagged/genus
https://latin.stackexchange.com/questions/tagged/grammar-choice
https://law.stackexchange.com
https://law.stackexchange.com/questions/65052/can-minors-express-their-political-views
https://law.stackexchange.com/questions/tagged/first-amendment
https://law.stackexchange.com/questions/tagged/minor
https://law.stackexchange.com/questions/tagged/political
https://law.stackexchange.com/questions/tagged/united-states
https://law.stackexchange.com/users/38224/cda
https://linguistics.stackexchange.com
https://linguistics.stackexchange.com/questions/39055/why-the-word-war-in-romance-languages-is-predominantly-of-germanic-origin-inst
https://linguistics.stackexchange.com/questions/tagged/etymology
https://linguistics.stackexchange.com/questions/tagged/latin
https://linguistics.stackexchange.com/questions/tagged/romance-languages
https://linguistics.stackexchange.com/users/32649/daniel-castro
https://literature.stackexchange.com
https://literature.stackexchange.com/questions/18660/what-literary-work-is-being-referred-to-in-this-limerick-in-which-the-earth-li
https://literature.stackexchange.com/questions/tagged/babar-the-elephant
https://literature.stackexchange.com/questions/tagged/jean-de-brunhoff
https://literature.stackexchange.com/questions/tagged/short-stories
https://literature.stackexchange.com/users/7399/aschultz
https://magento.stackexchange.com
https://martialarts.stackexchange.com
https://math.stackexchange.com
https://math.stackexchange.com/questions/4143094/let-fx-ax2bxc-a-b-c-in-r-suppose-fx-le1-fa-x-in-0-1-then-p
https://mathematica.stackexchange.com
https://mathematica.stackexchange.com/questions/246171/how-can-i-create-an-animation-showing-how-a-circular-sector-deformed-to-a-cone
https://mathematica.stackexchange.com/questions/246196/prevent-rasterization-of-a-simple-plot-with-a-colorfunction
https://mathematica.stackexchange.com/questions/tagged/drawing
https://mathematica.stackexchange.com/questions/tagged/graphics3d
https://mathematica.stackexchange.com/questions/tagged/image3d
https://mathematica.stackexchange.com/questions/tagged/plotting
https://mathematica.stackexchange.com/questions/tagged/rasterize
https://mathematica.stackexchange.com/users/42141/kim-jong-un
https://mathematica.stackexchange.com/users/73364/jasmine
https://mechanics.stackexchange.com
https://medicalsciences.stackexchange.com
https://medicalsciences.stackexchange.com/questions/tagged/covid-19
https://medicalsciences.stackexchange.com/questions/tagged/vaccination
https://medicalsciences.stackexchange.com/users/3302/arturo-don-juan
https://meta.stackexchange.com
https://money.stackexchange.com
https://movies.stackexchange.com
https://movies.stackexchange.com/questions/113628/why-does-the-roadrunner-say-beep-beep
https://movies.stackexchange.com/questions/tagged/jeopardy
https://movies.stackexchange.com/questions/tagged/looney-tunes
https://movies.stackexchange.com/questions/tagged/realism
https://movies.stackexchange.com/questions/tagged/sound-effects
https://movies.stackexchange.com/users/22993/sanpaco
https://movies.stackexchange.com/users/34973/barmar
https://music.stackexchange.com
https://music.stackexchange.com/questions/114473/low-eb-on-electric-bass
https://music.stackexchange.com/questions/114523/b-flat-major-triad-music-theory
https://music.stackexchange.com/questions/tagged/arranging
https://music.stackexchange.com/questions/tagged/bass-guitar
https://music.stackexchange.com/questions/tagged/piano
https://music.stackexchange.com/questions/tagged/sheet-music
https://music.stackexchange.com/questions/tagged/theory
https://music.stackexchange.com/users/61493/yerman
https://music.stackexchange.com/users/75986/alex
https://mythology.stackexchange.com
https://networkengineering.stackexchange.com
https://opendata.stackexchange.com
https://opensource.stackexchange.com/questions/11703/can-an-nda-block-gpl-freedom-number-4
https://opensource.stackexchange.com/questions/tagged/gpl-3
https://opensource.stackexchange.com/questions/tagged/license
https://opensource.stackexchange.com/questions/tagged/nda
https://outdoors.stackexchange.com
https://outdoors.stackexchange.com/questions/27113/do-i-need-a-rope-on-the-gro%c3%9fglockner
https://outdoors.stackexchange.com/users/12233/user1721135
https://parenting.stackexchange.com
https://pets.stackexchange.com
https://philosophy.stackexchange.com
https://photo.stackexchange.com
https://photo.stackexchange.com/questions/124876/how-to-check-if-a-photo-is-edited-even-basic-edits-like-exposure-and-white-bala
https://photo.stackexchange.com/questions/tagged/editing
https://photo.stackexchange.com/questions/tagged/lightroom
https://photo.stackexchange.com/questions/tagged/metadata
https://photo.stackexchange.com/questions/tagged/photo-editing
https://photo.stackexchange.com/questions/tagged/post-processing
https://photo.stackexchange.com/users/99191/prabhat
https://physics.stackexchange.com
https://physics.stackexchange.com/questions/636630/since-the-speed-of-light-is-constant-and-also-the-speed-limit-would-you-in-you
https://physics.stackexchange.com/questions/636926/why-is-it-said-that-antiparticles-are-a-result-of-combining-sr-with-quantum-theo
https://physics.stackexchange.com/questions/tagged/antimatter
https://physics.stackexchange.com/questions/tagged/faster-than-light
https://physics.stackexchange.com/questions/tagged/inertial-frames
https://physics.stackexchange.com/questions/tagged/lagrangian-formalism
https://physics.stackexchange.com/questions/tagged/mass
https://physics.stackexchange.com/questions/tagged/observers
https://physics.stackexchange.com/questions/tagged/particle-physics
https://physics.stackexchange.com/questions/tagged/photons
https://physics.stackexchange.com/questions/tagged/quantum-mechanics
https://physics.stackexchange.com/questions/tagged/rotational-dynamics
https://physics.stackexchange.com/questions/tagged/special-relativity
https://physics.stackexchange.com/questions/tagged/standard-model
https://poker.stackexchange.com
https://politics.stackexchange.com
https://politics.stackexchange.com/questions/64029/does-the-bds-movement-advocate-sanctions-against-the-united-states
https://politics.stackexchange.com/questions/64037/why-does-the-us-block-a-un-statement-calling-for-violence-to-stop-in-the-palesti
https://politics.stackexchange.com/questions/tagged/denmark
https://politics.stackexchange.com/questions/tagged/foreign-aid
https://politics.stackexchange.com/questions/tagged/israel
https://politics.stackexchange.com/questions/tagged/palestine
https://politics.stackexchange.com/questions/tagged/political-system
https://politics.stackexchange.com/questions/tagged/terminology
https://politics.stackexchange.com/questions/tagged/united-nations
https://politics.stackexchange.com/questions/tagged/united-states
https://politics.stackexchange.com/users/14853/obie-2-0
https://politics.stackexchange.com/users/23571/erwan
https://politics.stackexchange.com/users/29035/number-file
https://politics.stackexchange.com/users/38068/jmericks
https://politics.stackexchange.com/users/38391/productive-person
https://psychology.stackexchange.com
https://puzzling.stackexchange.com
https://puzzling.stackexchange.com/questions/110091/simulating-an-unbiased-coin-with-a-biased-one
https://puzzling.stackexchange.com/questions/110098/the-answer-may-not-make-sense-to-you
https://puzzling.stackexchange.com/questions/110101/dividing-a-chocolate-frosting-cake
https://puzzling.stackexchange.com/questions/tagged/geometry
https://puzzling.stackexchange.com/questions/tagged/knowledge
https://puzzling.stackexchange.com/questions/tagged/word
https://puzzling.stackexchange.com/users/34419/drd
https://puzzling.stackexchange.com/users/70292/pspl
https://raspberrypi.stackexchange.com
https://retrocomputing.stackexchange.com
https://retrocomputing.stackexchange.com/questions/19847/why-were-relays-prevalent-in-early-1940s-computers-when-vacuum-tubes-were-also-a
https://retrocomputing.stackexchange.com/questions/tagged/history
https://retrocomputing.stackexchange.com/questions/tagged/relay-computer
https://retrocomputing.stackexchange.com/questions/tagged/vacuum-tube
https://retrocomputing.stackexchange.com/users/10260/drsheldon
https://reverseengineering.stackexchange.com
https://rpg.stackexchange.com
https://rpg.stackexchange.com/questions/185160/do-potions-and-breakable-things-carried-by-a-character-break-or-are-damaged-when
https://rpg.stackexchange.com/questions/185165/does-the-wall-of-ice-block-line-of-sight
https://rpg.stackexchange.com/questions/185195/balance-implications-of-houseruled-megaman-warlock
https://rpg.stackexchange.com/questions/185199/can-i-combine-two-parts-of-a-sword-each-with-a-separate-infusion
https://rpg.stackexchange.com/questions/185201/is-this-an-ironclad-wish-i-wish-for-just-my-body-to-be-young-again-but-to-kee
https://rpg.stackexchange.com/questions/tagged/artificer
https://rpg.stackexchange.com/questions/tagged/artificer-infusions
https://rpg.stackexchange.com/questions/tagged/crafting
https://rpg.stackexchange.com/questions/tagged/dnd-5e
https://rpg.stackexchange.com/questions/tagged/eldritch-invocations
https://rpg.stackexchange.com/questions/tagged/falling
https://rpg.stackexchange.com/questions/tagged/homebrew-review
https://rpg.stackexchange.com/questions/tagged/line-of-sight
https://rpg.stackexchange.com/questions/tagged/potions
https://rpg.stackexchange.com/questions/tagged/spells
https://rpg.stackexchange.com/questions/tagged/wall
https://rpg.stackexchange.com/questions/tagged/warlock
https://rpg.stackexchange.com/questions/tagged/weapons
https://rpg.stackexchange.com/questions/tagged/wish
https://rpg.stackexchange.com/users/4563/kryan
https://rpg.stackexchange.com/users/55068/user55068
https://rpg.stackexchange.com/users/70646/toma
https://rpg.stackexchange.com/users/71201/adam-racho-5e
https://rus.stackexchange.com
https://russian.stackexchange.com
https://salesforce.stackexchange.com
https://scicomp.stackexchange.com
https://scifi.stackexchange.com
https://scifi.stackexchange.com/questions/247089/movie-about-man-who-is-teleported-to-mars
https://scifi.stackexchange.com/questions/tagged/books
https://scifi.stackexchange.com/questions/tagged/movie
https://scifi.stackexchange.com/questions/tagged/props
https://scifi.stackexchange.com/questions/tagged/star-trek
https://scifi.stackexchange.com/questions/tagged/star-trek-tos
https://scifi.stackexchange.com/questions/tagged/story-identification
https://scifi.stackexchange.com/questions/tagged/young-adult
https://scifi.stackexchange.com/users/140966/okprogrammer
https://scifi.stackexchange.com/users/140994/anonymous
https://security.stackexchange.com
https://sharepoint.stackexchange.com
https://sitecore.stackexchange.com
https://skeptics.stackexchange.com
https://softwareengineering.stackexchange.com
https://softwarerecs.stackexchange.com
https://sound.stackexchange.com
https://space.stackexchange.com
https://space.stackexchange.com/questions/52191/what-caused-all-the-dust-on-mars
https://space.stackexchange.com/questions/tagged/ingenuity
https://space.stackexchange.com/questions/tagged/mars
https://space.stackexchange.com/questions/tagged/regulatory
https://space.stackexchange.com/users/6501/tckosvic
https://spanish.stackexchange.com
https://sports.stackexchange.com
https://sqa.stackexchange.com
https://stackexchange.com
https://stackexchange.com/
https://stackexchange.com/?page=1
https://stackexchange.com/?page=2
https://stackexchange.com/?page=3
https://stackexchange.com/?page=4
https://stackexchange.com/?page=7
https://stackexchange.com/?pagesize=15
https://stackexchange.com/?pagesize=30
https://stackexchange.com/?pagesize=50
https://stackexchange.com/about
https://stackexchange.com/about/contact
https://stackexchange.com/digests
https://stackexchange.com/feeds/questions
https://stackexchange.com/feeds/sites
https://stackexchange.com/leagues
https://stackexchange.com/leagues/1/quarter/stackoverflow
https://stackexchange.com/leagues/1/week/stackoverflow
https://stackexchange.com/leagues/1/year/stackoverflow
https://stackexchange.com/leagues/101/month/stackapps
https://stackexchange.com/leagues/101/quarter/stackapps
https://stackexchange.com/leagues/101/week/stackapps
https://stackexchange.com/leagues/101/year/stackapps
https://stackexchange.com/leagues/102/alltime/ux
https://stackexchange.com/leagues/106/quarter/unix
https://stackexchange.com/leagues/106/week/unix
https://stackexchange.com/leagues/114/alltime/cstheory
https://stackexchange.com/leagues/114/quarter/cstheory
https://stackexchange.com/leagues/114/year/cstheory
https://stackexchange.com/leagues/118/month/apple
https://stackexchange.com/leagues/122/alltime/rpg
https://stackexchange.com/leagues/122/quarter/rpg
https://stackexchange.com/leagues/126/year/bicycles
https://stackexchange.com/leagues/131/month/softwareengineering
https://stackexchange.com/leagues/131/quarter/softwareengineering
https://stackexchange.com/leagues/131/week/softwareengineering
https://stackexchange.com/leagues/131/year/softwareengineering
https://stackexchange.com/leagues/135/alltime/electronics
https://stackexchange.com/leagues/135/quarter/electronics
https://stackexchange.com/leagues/135/year/electronics
https://stackexchange.com/leagues/139/week/android
https://stackexchange.com/leagues/139/year/android
https://stackexchange.com/leagues/147/alltime/boardgames
https://stackexchange.com/leagues/147/month/boardgames
https://stackexchange.com/leagues/147/quarter/boardgames
https://stackexchange.com/leagues/151/alltime/physics
https://stackexchange.com/leagues/151/month/physics
https://stackexchange.com/leagues/151/quarter/physics
https://stackexchange.com/leagues/151/year/physics
https://stackexchange.com/leagues/162/alltime/security
https://stackexchange.com/leagues/166/month/writing
https://stackexchange.com/leagues/166/week/writing
https://stackexchange.com/leagues/170/month/video
https://stackexchange.com/leagues/174/quarter/graphicdesign
https://stackexchange.com/leagues/174/week/graphicdesign
https://stackexchange.com/leagues/182/month/dba
https://stackexchange.com/leagues/182/quarter/dba
https://stackexchange.com/leagues/186/alltime/scifi
https://stackexchange.com/leagues/186/month/scifi
https://stackexchange.com/leagues/186/quarter/scifi
https://stackexchange.com/leagues/186/week/scifi
https://stackexchange.com/leagues/186/year/scifi
https://stackexchange.com/leagues/2/alltime/serverfault
https://stackexchange.com/leagues/2/month/serverfault
https://stackexchange.com/leagues/2/week/serverfault
https://stackexchange.com/leagues/2/year/serverfault
https://stackexchange.com/leagues/200/year/codegolf
https://stackexchange.com/leagues/208/year/pm
https://stackexchange.com/leagues/212/week/skeptics
https://stackexchange.com/leagues/216/alltime/fitness
https://stackexchange.com/leagues/216/month/fitness
https://stackexchange.com/leagues/216/week/fitness
https://stackexchange.com/leagues/216/year/fitness
https://stackexchange.com/leagues/220/month/drupal
https://stackexchange.com/leagues/220/quarter/drupal
https://stackexchange.com/leagues/224/quarter/mechanics
https://stackexchange.com/leagues/240/quarter/music
https://stackexchange.com/leagues/240/week/music
https://stackexchange.com/leagues/240/year/music
https://stackexchange.com/leagues/244/week/sqa
https://stackexchange.com/leagues/248/month/judaism
https://stackexchange.com/leagues/248/week/judaism
https://stackexchange.com/leagues/253/alltime/german
https://stackexchange.com/leagues/253/month/german
https://stackexchange.com/leagues/253/quarter/german
https://stackexchange.com/leagues/253/week/german
https://stackexchange.com/leagues/257/month/japanese
https://stackexchange.com/leagues/257/week/japanese
https://stackexchange.com/leagues/265/alltime/philosophy
https://stackexchange.com/leagues/265/month/philosophy
https://stackexchange.com/leagues/265/year/philosophy
https://stackexchange.com/leagues/269/quarter/gardening
https://stackexchange.com/leagues/269/week/gardening
https://stackexchange.com/leagues/273/alltime/travel
https://stackexchange.com/leagues/273/quarter/travel
https://stackexchange.com/leagues/281/week/crypto
https://stackexchange.com/leagues/295/alltime/dsp
https://stackexchange.com/leagues/295/quarter/dsp
https://stackexchange.com/leagues/299/week/french
https://stackexchange.com/leagues/308/quarter/bitcoin
https://stackexchange.com/leagues/312/week/linguistics
https://stackexchange.com/leagues/320/alltime/hermeneutics
https://stackexchange.com/leagues/320/month/hermeneutics
https://stackexchange.com/leagues/320/year/hermeneutics
https://stackexchange.com/leagues/324/quarter/history
https://stackexchange.com/leagues/324/year/history
https://stackexchange.com/leagues/336/alltime/bricks
https://stackexchange.com/leagues/336/week/bricks
https://stackexchange.com/leagues/336/year/bricks
https://stackexchange.com/leagues/34/week/webapps
https://stackexchange.com/leagues/353/alltime/spanish
https://stackexchange.com/leagues/353/month/spanish
https://stackexchange.com/leagues/353/year/spanish
https://stackexchange.com/leagues/363/month/scicomp
https://stackexchange.com/leagues/363/year/scicomp
https://stackexchange.com/leagues/367/alltime/movies
https://stackexchange.com/leagues/367/quarter/movies
https://stackexchange.com/leagues/367/year/movies
https://stackexchange.com/leagues/371/quarter/chinese
https://stackexchange.com/leagues/371/year/chinese
https://stackexchange.com/leagues/375/alltime/biology
https://stackexchange.com/leagues/375/month/biology
https://stackexchange.com/leagues/379/alltime/poker
https://stackexchange.com/leagues/379/quarter/poker
https://stackexchange.com/leagues/379/year/poker
https://stackexchange.com/leagues/387/week/mathematica
https://stackexchange.com/leagues/387/year/mathematica
https://stackexchange.com/leagues/391/quarter/psychology
https://stackexchange.com/leagues/395/month/outdoors
https://stackexchange.com/leagues/395/quarter/outdoors
https://stackexchange.com/leagues/4/alltime/meta
https://stackexchange.com/leagues/4/quarter/meta
https://stackexchange.com/leagues/403/quarter/martialarts
https://stackexchange.com/leagues/403/year/martialarts
https://stackexchange.com/leagues/411/alltime/sports
https://stackexchange.com/leagues/411/month/sports
https://stackexchange.com/leagues/415/month/academia
https://stackexchange.com/leagues/415/quarter/academia
https://stackexchange.com/leagues/415/week/academia
https://stackexchange.com/leagues/419/quarter/cs
https://stackexchange.com/leagues/423/alltime/workplace
https://stackexchange.com/leagues/423/quarter/workplace
https://stackexchange.com/leagues/431/alltime/chemistry
https://stackexchange.com/leagues/431/month/chemistry
https://stackexchange.com/leagues/431/quarter/chemistry
https://stackexchange.com/leagues/431/year/chemistry
https://stackexchange.com/leagues/435/alltime/chess
https://stackexchange.com/leagues/435/week/chess
https://stackexchange.com/leagues/447/month/raspberrypi
https://stackexchange.com/leagues/447/week/raspberrypi
https://stackexchange.com/leagues/45/week/webmasters
https://stackexchange.com/leagues/451/alltime/russian
https://stackexchange.com/leagues/451/year/russian
https://stackexchange.com/leagues/455/quarter/islam
https://stackexchange.com/leagues/455/week/islam
https://stackexchange.com/leagues/455/year/islam
https://stackexchange.com/leagues/459/year/salesforce
https://stackexchange.com/leagues/463/alltime/patents
https://stackexchange.com/leagues/463/month/patents
https://stackexchange.com/leagues/467/alltime/genealogy
https://stackexchange.com/leagues/467/quarter/genealogy
https://stackexchange.com/leagues/469/alltime/robotics
https://stackexchange.com/leagues/469/quarter/robotics
https://stackexchange.com/leagues/471/alltime/expressionengine
https://stackexchange.com/leagues/471/year/expressionengine
https://stackexchange.com/leagues/475/month/politics
https://stackexchange.com/leagues/475/year/politics
https://stackexchange.com/leagues/477/alltime/anime
https://stackexchange.com/leagues/477/month/anime
https://stackexchange.com/leagues/477/year/anime
https://stackexchange.com/leagues/479/week/magento
https://stackexchange.com/leagues/479/year/magento
https://stackexchange.com/leagues/481/quarter/ell
https://stackexchange.com/leagues/481/week/ell
https://stackexchange.com/leagues/483/alltime/sustainability
https://stackexchange.com/leagues/483/month/sustainability
https://stackexchange.com/leagues/483/year/sustainability
https://stackexchange.com/leagues/485/week/tridion
https://stackexchange.com/leagues/485/year/tridion
https://stackexchange.com/leagues/489/year/reverseengineering
https://stackexchange.com/leagues/49/month/cooking
https://stackexchange.com/leagues/49/quarter/cooking
https://stackexchange.com/leagues/49/week/cooking
https://stackexchange.com/leagues/496/alltime/networkengineering
https://stackexchange.com/leagues/496/year/networkengineering
https://stackexchange.com/leagues/498/month/opendata
https://stackexchange.com/leagues/498/quarter/opendata
https://stackexchange.com/leagues/498/week/opendata
https://stackexchange.com/leagues/500/alltime/freelancing
https://stackexchange.com/leagues/500/month/freelancing
https://stackexchange.com/leagues/500/year/freelancing
https://stackexchange.com/leagues/502/month/blender
https://stackexchange.com/leagues/502/quarter/blender
https://stackexchange.com/leagues/502/week/blender
https://stackexchange.com/leagues/504/month/mathoverflow
https://stackexchange.com/leagues/504/quarter/mathoverflow
https://stackexchange.com/leagues/504/year/mathoverflow
https://stackexchange.com/leagues/508/quarter/space
https://stackexchange.com/leagues/508/year/space
https://stackexchange.com/leagues/512/month/sound
https://stackexchange.com/leagues/512/quarter/sound
https://stackexchange.com/leagues/512/week/sound
https://stackexchange.com/leagues/512/year/sound
https://stackexchange.com/leagues/514/quarter/astronomy
https://stackexchange.com/leagues/516/month/tor
https://stackexchange.com/leagues/518/alltime/pets
https://stackexchange.com/leagues/518/year/pets
https://stackexchange.com/leagues/520/week/ham
https://stackexchange.com/leagues/520/year/ham
https://stackexchange.com/leagues/524/month/italian
https://stackexchange.com/leagues/524/quarter/italian
https://stackexchange.com/leagues/524/week/italian
https://stackexchange.com/leagues/526/year/pt-stackoverflow
https://stackexchange.com/leagues/528/quarter/aviation
https://stackexchange.com/leagues/53/quarter/gamedev
https://stackexchange.com/leagues/53/year/gamedev
https://stackexchange.com/leagues/530/alltime/ebooks
https://stackexchange.com/leagues/530/month/ebooks
https://stackexchange.com/leagues/530/quarter/ebooks
https://stackexchange.com/leagues/530/year/ebooks
https://stackexchange.com/leagues/532/alltime/alcohol
https://stackexchange.com/leagues/532/month/alcohol
https://stackexchange.com/leagues/532/year/alcohol
https://stackexchange.com/leagues/536/month/softwarerecs
https://stackexchange.com/leagues/536/year/softwarerecs
https://stackexchange.com/leagues/540/alltime/arduino
https://stackexchange.com/leagues/540/quarter/arduino
https://stackexchange.com/leagues/540/year/arduino
https://stackexchange.com/leagues/546/alltime/expatriates
https://stackexchange.com/leagues/546/week/expatriates
https://stackexchange.com/leagues/546/year/expatriates
https://stackexchange.com/leagues/548/week/matheducators
https://stackexchange.com/leagues/553/alltime/earthscience
https://stackexchange.com/leagues/553/month/earthscience
https://stackexchange.com/leagues/553/quarter/earthscience
https://stackexchange.com/leagues/553/year/earthscience
https://stackexchange.com/leagues/555/alltime/joomla
https://stackexchange.com/leagues/555/week/joomla
https://stackexchange.com/leagues/557/quarter/datascience
https://stackexchange.com/leagues/557/year/datascience
https://stackexchange.com/leagues/559/month/puzzling
https://stackexchange.com/leagues/563/quarter/craftcms
https://stackexchange.com/leagues/565/alltime/buddhism
https://stackexchange.com/leagues/565/quarter/buddhism
https://stackexchange.com/leagues/565/week/buddhism
https://stackexchange.com/leagues/567/month/hinduism
https://stackexchange.com/leagues/567/year/hinduism
https://stackexchange.com/leagues/571/alltime/communitybuilding
https://stackexchange.com/leagues/579/alltime/worldbuilding
https://stackexchange.com/leagues/579/month/worldbuilding
https://stackexchange.com/leagues/579/week/worldbuilding
https://stackexchange.com/leagues/579/year/worldbuilding
https://stackexchange.com/leagues/581/alltime/ja-stackoverflow
https://stackexchange.com/leagues/583/alltime/emacs
https://stackexchange.com/leagues/583/year/emacs
https://stackexchange.com/leagues/587/month/hsm
https://stackexchange.com/leagues/587/week/hsm
https://stackexchange.com/leagues/587/year/hsm
https://stackexchange.com/leagues/591/quarter/economics
https://stackexchange.com/leagues/593/alltime/lifehacks
https://stackexchange.com/leagues/593/week/lifehacks
https://stackexchange.com/leagues/595/alltime/engineering
https://stackexchange.com/leagues/595/month/engineering
https://stackexchange.com/leagues/595/quarter/engineering
https://stackexchange.com/leagues/595/year/engineering
https://stackexchange.com/leagues/597/alltime/coffee
https://stackexchange.com/leagues/597/month/coffee
https://stackexchange.com/leagues/597/quarter/coffee
https://stackexchange.com/leagues/597/week/coffee
https://stackexchange.com/leagues/599/alltime/vi
https://stackexchange.com/leagues/599/week/vi
https://stackexchange.com/leagues/601/week/musicfans
https://stackexchange.com/leagues/605/quarter/civicrm
https://stackexchange.com/leagues/607/quarter/medicalsciences
https://stackexchange.com/leagues/607/week/medicalsciences
https://stackexchange.com/leagues/607/year/medicalsciences
https://stackexchange.com/leagues/609/year/ru-stackoverflow
https://stackexchange.com/leagues/61/month/photo
https://stackexchange.com/leagues/61/quarter/photo
https://stackexchange.com/leagues/61/week/photo
https://stackexchange.com/leagues/613/alltime/rus
https://stackexchange.com/leagues/613/quarter/rus
https://stackexchange.com/leagues/613/week/rus
https://stackexchange.com/leagues/613/year/rus
https://stackexchange.com/leagues/615/week/mythology
https://stackexchange.com/leagues/615/year/mythology
https://stackexchange.com/leagues/619/quarter/opensource
https://stackexchange.com/leagues/619/week/opensource
https://stackexchange.com/leagues/621/week/elementaryos
https://stackexchange.com/leagues/625/alltime/portuguese
https://stackexchange.com/leagues/633/month/computergraphics
https://stackexchange.com/leagues/633/week/computergraphics
https://stackexchange.com/leagues/635/alltime/hardwarerecs
https://stackexchange.com/leagues/635/quarter/hardwarerecs
https://stackexchange.com/leagues/635/week/hardwarerecs
https://stackexchange.com/leagues/637/quarter/es-stackoverflow
https://stackexchange.com/leagues/640/week/3dprinting
https://stackexchange.com/leagues/640/year/3dprinting
https://stackexchange.com/leagues/642/quarter/ethereum
https://stackexchange.com/leagues/642/week/ethereum
https://stackexchange.com/leagues/644/alltime/latin
https://stackexchange.com/leagues/644/week/latin
https://stackexchange.com/leagues/646/year/languagelearning
https://stackexchange.com/leagues/65/alltime/stats
https://stackexchange.com/leagues/65/week/stats
https://stackexchange.com/leagues/650/week/crafts
https://stackexchange.com/leagues/654/week/korean
https://stackexchange.com/leagues/654/year/korean
https://stackexchange.com/leagues/656/month/monero
https://stackexchange.com/leagues/656/quarter/monero
https://stackexchange.com/leagues/658/month/ai
https://stackexchange.com/leagues/658/week/ai
https://stackexchange.com/leagues/658/year/ai
https://stackexchange.com/leagues/662/alltime/esperanto
https://stackexchange.com/leagues/662/month/esperanto
https://stackexchange.com/leagues/662/quarter/esperanto
https://stackexchange.com/leagues/662/week/esperanto
https://stackexchange.com/leagues/664/alltime/sitecore
https://stackexchange.com/leagues/664/quarter/sitecore
https://stackexchange.com/leagues/664/year/sitecore
https://stackexchange.com/leagues/668/quarter/literature
https://stackexchange.com/leagues/668/year/literature
https://stackexchange.com/leagues/670/alltime/vegetarianism
https://stackexchange.com/leagues/670/quarter/vegetarianism
https://stackexchange.com/leagues/672/week/ukrainian
https://stackexchange.com/leagues/674/alltime/devops
https://stackexchange.com/leagues/674/month/devops
https://stackexchange.com/leagues/674/year/devops
https://stackexchange.com/leagues/676/alltime/bioinformatics
https://stackexchange.com/leagues/676/week/bioinformatics
https://stackexchange.com/leagues/678/alltime/cseducators
https://stackexchange.com/leagues/678/month/cseducators
https://stackexchange.com/leagues/678/quarter/cseducators
https://stackexchange.com/leagues/678/year/cseducators
https://stackexchange.com/leagues/680/month/interpersonal
https://stackexchange.com/leagues/684/alltime/iota
https://stackexchange.com/leagues/684/month/iota
https://stackexchange.com/leagues/684/week/iota
https://stackexchange.com/leagues/686/year/stellar
https://stackexchange.com/leagues/69/alltime/math
https://stackexchange.com/leagues/69/year/math
https://stackexchange.com/leagues/692/month/conlang
https://stackexchange.com/leagues/692/quarter/conlang
https://stackexchange.com/leagues/692/year/conlang
https://stackexchange.com/leagues/694/quarter/quantumcomputing
https://stackexchange.com/leagues/694/year/quantumcomputing
https://stackexchange.com/leagues/696/alltime/eosio
https://stackexchange.com/leagues/696/month/eosio
https://stackexchange.com/leagues/696/quarter/eosio
https://stackexchange.com/leagues/696/week/eosio
https://stackexchange.com/leagues/698/month/tezos
https://stackexchange.com/leagues/698/quarter/tezos
https://stackexchange.com/leagues/698/week/tezos
https://stackexchange.com/leagues/700/week/or
https://stackexchange.com/leagues/702/alltime/drones
https://stackexchange.com/leagues/702/month/drones
https://stackexchange.com/leagues/702/quarter/drones
https://stackexchange.com/leagues/702/week/drones
https://stackexchange.com/leagues/704/alltime/mattermodeling
https://stackexchange.com/leagues/704/month/mattermodeling
https://stackexchange.com/leagues/704/year/mattermodeling
https://stackexchange.com/leagues/73/alltime/diy
https://stackexchange.com/leagues/73/quarter/diy
https://stackexchange.com/leagues/79/alltime/gis
https://stackexchange.com/leagues/79/quarter/gis
https://stackexchange.com/leagues/79/week/gis
https://stackexchange.com/leagues/79/year/gis
https://stackexchange.com/leagues/85/alltime/tex
https://stackexchange.com/leagues/85/month/tex
https://stackexchange.com/leagues/85/week/tex
https://stackexchange.com/leagues/85/year/tex
https://stackexchange.com/leagues/89/alltime/askubuntu
https://stackexchange.com/leagues/89/month/askubuntu
https://stackexchange.com/leagues/97/quarter/english
https://stackexchange.com/leagues/97/week/english
https://stackexchange.com/questions/tagged/daisies
https://stackexchange.com/questions/tagged/unicorns
https://stackexchange.com/questions?tab=realtime
https://stackexchange.com/sites
https://stackexchange.com/sites#culturerecreation
https://stackexchange.com/sites#lifearts
https://stackexchange.com/sites#science
https://stackexchange.com/sites#technology
https://stackexchange.com/sites?view=grid
https://stackexchange.com/template
https://stackexchange.com/tour
https://stackexchange.com/users/login
https://stackexchange.com/users/login#create-account
https://stackexchange.com/users/login?ssrc=head&returnurl=https%3a%2f%2fstackexchange.com
https://stats.stackexchange.com
https://stats.stackexchange.com/questions/524730/finding-mme-for-a-sample-with-known-pmf
https://stats.stackexchange.com/questions/tagged/estimators
https://stats.stackexchange.com/questions/tagged/maximum-likelihood
https://stats.stackexchange.com/questions/tagged/self-study
https://stats.stackexchange.com/users/231987/faisal-mustafa
https://tex.stackexchange.com
https://tex.stackexchange.com/questions/tagged/nodes
https://tex.stackexchange.com/users/72015/dnraikes
https://travel.stackexchange.com
https://unix.stackexchange.com
https://unix.stackexchange.com/questions/649996/is-dd-a-reliable-tool-to-make-an-ssd-image
https://unix.stackexchange.com/questions/650072/move-all-files-except-one-that-matches-filename
https://unix.stackexchange.com/questions/tagged/find
https://unix.stackexchange.com/questions/tagged/hard-disk
https://unix.stackexchange.com/questions/tagged/less
https://unix.stackexchange.com/questions/tagged/mv
https://unix.stackexchange.com/users/189721/westerngun
https://unix.stackexchange.com/users/441178/user2300940
https://ux.stackexchange.com
https://vi.stackexchange.com
https://video.stackexchange.com
https://webapps.stackexchange.com
https://webmasters.stackexchange.com
https://windowsphone.stackexchange.com
https://woodworking.stackexchange.com
https://wordpress.stackexchange.com
https://workplace.stackexchange.com
https://workplace.stackexchange.com/questions/172539/servicing-customers-with-disagreeable-content
https://workplace.stackexchange.com/questions/172547/how-do-i-improve-communication-with-a-person-whose-grammar-is-so-bad-that-i-some
https://workplace.stackexchange.com/questions/tagged/communication
https://workplace.stackexchange.com/questions/tagged/discrimination
https://workplace.stackexchange.com/questions/tagged/ethics
https://workplace.stackexchange.com/questions/tagged/professionalism
https://workplace.stackexchange.com/questions/tagged/united-states
https://workplace.stackexchange.com/users/126081/nocari%c3%b1o
https://workplace.stackexchange.com/users/126086/amy-fiori
https://worldbuilding.stackexchange.com
https://worldbuilding.stackexchange.com/questions/202740/how-to-limit-the-usefulness-of-an-anti-gravity-mineral-to-airship-construction-i
https://worldbuilding.stackexchange.com/questions/202822/how-could-an-elected-official-be-made-anatomically-different-to-the-rest-of-soci
https://worldbuilding.stackexchange.com/questions/202834/least-impossible-explanation-for-superhero-flight
https://worldbuilding.stackexchange.com/questions/tagged/biology
https://worldbuilding.stackexchange.com/questions/tagged/creature-design
https://worldbuilding.stackexchange.com/questions/tagged/fantasy-races
https://worldbuilding.stackexchange.com/questions/tagged/industrial-age
https://worldbuilding.stackexchange.com/questions/tagged/lasers
https://worldbuilding.stackexchange.com/questions/tagged/military
https://worldbuilding.stackexchange.com/questions/tagged/steampunk
https://worldbuilding.stackexchange.com/questions/tagged/super-powers
https://worldbuilding.stackexchange.com/questions/tagged/vampires
https://worldbuilding.stackexchange.com/users/18117/guran
https://worldbuilding.stackexchange.com/users/75161/ichthys-king
https://worldbuilding.stackexchange.com/users/80125/darth-biomech
https://worldbuilding.stackexchange.com/users/85480/off-kilter
https://writing.stackexchange.com/questions/tagged/characters
https://writing.stackexchange.com/questions/tagged/creative-writing
https://writing.stackexchange.com/questions/tagged/fantasy
